### ISSUE TITLE
Conversion sometimes works only partly 

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#43] opened 2019-01-13 04:21 UTC
e.g. https://tools.wmflabs.org/author-disambiguator/?name=Ph.+Schwemling&doit=Look+for+author&limit=50&filter=wdt%3AP2093+%22Ph.+Schwemling%22
resulted in just one item being edited, despite 50 having been marked.

**Comment by arthurpsmith** [comment] 2019-01-14 15:02
Whoah, that's broken. Looking into it now!

**Comment by arthurpsmith** [comment] 2019-01-14 15:19
Ok, the problem is again coming from the wikidata API - it's not responding or somehow failing to create the entries for most (all but one in this case!) of the manuscripts. I'm relying on that to do the Quickstatements conversion. Hmmm...

**Comment by arthurpsmith** [comment] 2019-01-15 17:55
Hmm, thought  had a fix for this, but I had to roll it back. Still looking into it...

**Closed as completed** 2019-01-15 18:26 UTC
