### ISSUE TITLE
Suggestions seemingly unrelated to input

### ISSUE THREAD

**Issue by Daniel-Mietchen** [arthurpsmith/author-disambiguator#108] opened 2019-12-17 05:41 UTC
E.g. for the string "Timothy J Steiner", I get the suggestion "[Christopher R Sudfeld](https://tools.wmflabs.org/author-disambiguator/author_item.php?id=Q74039797)" for the article "[Disability-adjusted life years (DALYs) for 291 diseases and injuries in 21 regions, 1990-2010: a systematic analysis for the Global Burden of Disease Study 2010](https://tools.wmflabs.org/author-disambiguator/work_item.php?id=Q27860791)"

I thought I had opened a ticket for similar cases in the past, but could not find that right now, so starting a new one.

<img width="1153" alt="Screen Shot 2019-12-17 at 00 37 46" src="https://user-images.githubusercontent.com/465923/70967827-8007c500-2065-11ea-86f4-383d3117a87e.png">

**Comment by arthurpsmith** [comment] 2019-12-17 13:53
This is always caused by either an alternate label or a "stated as" where the name does not match. In this case the problem is in https://www.wikidata.org/wiki/Q28111913 - look for Sudfield in the "authos" section and you will find a qualifier "stated as" "Timothy Steiner". This appears to be caused by an edit YOU made with Quickstatements back in November.

**Comment by Daniel-Mietchen** [comment] 2019-12-18 13:29
Thanks for digging into it. I had checked for labels and aliases but not for "stated as". The corresponding edit was the [last one](https://tools.wmflabs.org/editgroups/b/QSv2/21136/) from [this batch](https://tools.wmflabs.org/quickstatements/#/batch/21136), which looks normal otherwise.

That item Q28111913, on the other hand, has a number of problems where author name strings and items do not match. 

This, in turn, seems to be due to 
 - a different arrangement of the author list in PubMed and Crossref between
https://www.wikidata.org/w/index.php?title=Q28281577&oldid=447323384 (Steiner 308, Sudfield 311) and https://www.wikidata.org/w/index.php?title=Q28111913&oldid=452966634 (Steiner 311, Sudfield 314)
- a merge at https://www.wikidata.org/w/index.php?title=Q28111913&type=revision&diff=453698499&oldid=452966634

Will get back to this later.

**Comment by arthurpsmith** [comment] 2020-02-20 14:59
I'm wondering if it might help for the author-item page(s) to show all the "stated as" strings to make this a little easier to find... This is a general issue I'm not quite sure how to display clearly, when for a work we have a list of authors with their English labels but also the "stated as" strings, should both be shown somehow?

**Comment by arthurpsmith** [comment] 2020-10-06 17:48
I've added description, id's, aliases and "stated as" names for authors to the main author item display. Closing!

**Closed by arthurpsmith** 2020-10-06 17:48 UTC
